### ISSUE TITLE
freeRADIUS: Add the support for custom reply messages

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/mobileid#69]
In order to provide active feedback about the Mobile ID related status the `Reply-Message`could be filled out with proper information.

```
post-auth {
    Post-Auth-Type REJECT {
        update reply {
            Reply-Message = "Your password is wrong, prepare to be eaten by flying monkeys."
        }
    }
}
```

http://lists.freeradius.org/pipermail/freeradius-users/2011-May/053542.html

**Comment by jatinnijash** [comment]
I want Meaningful Reply-Message for Access-Reject in freeradius 3.0 like 

1.Your User Expired
2.Your User Disable
3.Wrong Mac Address
4.Wrong Password
5.Username not Found

anyone help me please

**Comment by FreddyKaiser** [comment]
> I want Meaningful Reply-Message for Access-Reject in freeradius 3.0 like
> 
> 1.Your User Expired
> 2.Your User Disable
> 3.Wrong Mac Address
> 4.Wrong Password
> 5.Username not Found
> 
> anyone help me please
Check this or similar posts https://grasehotspot.org/documentation/freeradius/meaningful-reply-message-for-access-reject/
